apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: qovm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qovm
    app.kubernetes.io/part-of: byoc-app-covk
  name: qovm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: qovm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: qovm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-aghv-tenant/byoc-app-covk/qovm@sha256:25c8e1a65bf0f3684fc070d7b7a450fbb523b29782a8bcc73ceb9f3c05cd3b1a
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
